### ISSUE TITLE
Shared Context w/ X509 Cert Store

### ISSUE THREAD

**Issue by rphillips** [zhaozg/lua-openssl#57]
I think we should add a test for a shared context, similar to the current test [1], where the x509 certificate store gets set on the shared context. We are still seeing crashes regarding this use case.

[1] https://github.com/zhaozg/lua-openssl/blob/master/test/8.ssl_c.lua

**Comment by zhaozg** [comment]
accepted, and sorry for crash

**Comment by rphillips** [comment]
Not a problem... I'll see about writing the test case, but I'm bouncing around on different things.

**Comment by zhaozg** [comment]
simply add some cert_store support, https://github.com/zhaozg/lua-openssl/blob/master/test/8.ssl_c.lua#L20-L25,

**Comment by rphillips** [comment]
no crashes?

**Comment by zhaozg** [comment]
no crash on Windows openssl 1.0.2, 
I will do more test on linux

**Comment by zhaozg** [comment]
I reproduce this bug, and will fix it later.
```
[zhaozg@kkhub test]$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
[zhaozg@kkhub test]$ uname -a
Linux kkhub.com 2.6.32-431.20.3.el6.x86_64 #1 SMP Thu Jun 19 21:14:45 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by zhaozg** [comment]
Hi @rphillips, 
I regret to give up the repair the Bug, because in the OpenSSL 1.0.1 and old version, I can not simply  implicate the shared certstore object, so in the lua-opensl,  ssl_ctx object will not support certstore object.
I  recommend to use shared ssl_ctx object,  or  use the latest openssl release 1.0.2. 

References of X509_STORE(https://github.com/openssl/openssl/blob/OpenSSL_1_0_1-stable/crypto/x509/x509_vfy.h#L183-L212
) is missing to be managed.

https://github.com/openssl/openssl/blob/OpenSSL_1_0_1-stable/crypto/x509/x509_lu.c#L182-L252  VS https://github.com/openssl/openssl/blob/OpenSSL_1_0_1-stable/crypto/x509/x509_lu.c#L182-L252
