### ISSUE TITLE
EC evp_pkey:parse().ec:parse() should return a table with curve parameters

### ISSUE THREAD

**Issue by dol** [zhaozg/lua-openssl#67]
While writing a test for [EC pkeys](https://github.com/dol/lua-openssl/blob/b77fc25a923339a87423b00a70e8c4f9374b0535/test/ec.lua) I came across an inconsistency.

```
local pkey = require'openssl'.pkey
local unpack = unpack or table.unpack
local inspect = require 'inspect'

local nec =  {'ec','prime256v1'}
local ec_key = pkey.new(unpack(nec))
local curve_params = ec_key:parse().ec:parse()
print(inspect(curve_params))
curve_params.alg = 'ec'
pkey.new(curve_params)
```

```
Expected result:
----------------
{
  ec_name = 415,
  x = <userdata 1>,
  y = <userdata 2>,
  d =  <userdata 3>
}
```

```
Actual result:
--------------
{
  conv_form = 4,
  enc_flag = 0,
  group = <userdata 1>,
  priv_key = <userdata 2>,
  pub_key = <userdata 3>
}
```

The expected behavior is to return a table with the curve parameters. To make the behavior comparably to RSA and DSA keys.

My proposal is to extend the openssl.ec_key key with a group parameter. openssl.ec_key.parse() would return the expected table.

**Comment by zhaozg** [comment]
I make ec:parse() to return a table to describe ec_key_st(EC_KEY) structure with openssl style, that EC_KEY more complex than RSA struct, so lead to this result. no reasonable to extract to basic structure, because which can be fetch from group, priv_key and pub_key field.

please check struct ec_key_st in crypto/ec/ec_lcl.h in openssl source.
Are you persist to this issue?

**Comment by zhaozg** [comment]
as you except, you can local curve_params = ec_key:parse().ec:parse(true) to get basic result

**Comment by dol** [comment]
thx. Much appreciated.
